#define n_tel 2
#define n_cook 2
#define n_oven 10
#define n_deliverer 10
#define t_orderlow 1
#define t_orderhigh 5
#define n_orderlow 1
#define n_orderhigh 5
#define Pm 35
#define Pp 25
#define Ps 40
#define t_paymentlow 1
#define t_paymenthigh 3
#define p_fail 5
#define Cm 10
#define Cp 11
#define Cs 12
#define t_prep 1
#define t_bake 10
#define t_pack 1
#define t_dellow 5
#define t_delhigh 15
